services:
  grafana:
    user: root
    container_name: "innius-grpc-datasource"

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/root/innius-grpc-datasource
      - ./dist:/var/lib/grafana/plugins/innius-grpc-datasource
      - ./provisioning:/etc/grafana/provisioning

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.innius-grpc-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: innius-grpc-datasource
